# Generated by Django 3.2.9 on 2022-05-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoraExtraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionariomodel')),
            ],
            options={
                'verbose_name': 'Registro Hora Extra',
                'verbose_name_plural': 'Registros Horas Extras',
                'db_table': 'projeto_rh"."registro_hora_extra',
                'managed': True,
            },
        ),
    ]
